/* GENERATED by scripts/build-fonts.py — do not edit by hand. */
/**
 * The shipped font files and the exact set of characters each family can draw.
 *
 * `coverage` is read back out of the woff2 that ships — it is the file's own
 * `cmap`, not a restatement of what was asked for. `src/lib/fonts.ts` turns it
 * into a compile-time guard and `src/lib/fonts.test.mts` checks it against
 * every string in `messages/` and `src/content/`.
 */

export interface FontSubsetFile {
  /** Public URL. Content-hashed, so it is safe to cache forever. */
  readonly file: string;
  readonly bytes: number;
}

export interface GeneratedFamily {
  readonly family: string;
  readonly latin: FontSubsetFile;
  readonly cyrillic: FontSubsetFile;
}

export const serifFiles = {
  family: "Literata",
  latin: { file: "/fonts/literata-latin.ff3f34fe71.woff2", bytes: 26120 },
  cyrillic: { file: "/fonts/literata-cyrillic.7c744e7917.woff2", bytes: 12476 },
} as const satisfies GeneratedFamily;

export const sansFiles = {
  family: "Commissioner",
  latin: { file: "/fonts/commissioner-latin.a938206a15.woff2", bytes: 28852 },
  cyrillic: { file: "/fonts/commissioner-cyrillic.2f7799b73e.woff2", bytes: 21240 },
} as const satisfies GeneratedFamily;

/** Every character the display face can draw, both subsets unioned. */
export const serifCoverage =
  " !\u0022#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\u005C]^_`abcdefghijklmnopqrstuvwxyz{|}~\u00A0\u00A7\u00A9\u00AB\u00AD\u00B0\u00B7\u00BB\u00C2\u00C9\u00CE\u00D7\u00E2\u00E9\u00EE\u00F7\u0102\u0103\u015E\u015F\u0162\u0163\u0218\u0219\u021A\u021B\u0401\u0410\u0411\u0412\u0413\u0414\u0415\u0416\u0417\u0418\u0419\u041A\u041B\u041C\u041D\u041E\u041F\u0420\u0421\u0422\u0423\u0424\u0425\u0426\u0427\u0428\u0429\u042A\u042B\u042C\u042D\u042E\u042F\u0430\u0431\u0432\u0433\u0434\u0435\u0436\u0437\u0438\u0439\u043A\u043B\u043C\u043D\u043E\u043F\u0440\u0441\u0442\u0443\u0444\u0445\u0446\u0447\u0448\u0449\u044A\u044B\u044C\u044D\u044E\u044F\u0451\u2010\u2013\u2014\u2015\u2018\u2019\u201A\u201C\u201D\u201E\u2022\u2026\u2030\u2039\u203A\u20AC\u2116\u2122\u2190\u2191\u2192\u2193\u2212\u2264\u2265";

/** Every character the body face can draw, both subsets unioned. */
export const sansCoverage =
  " !\u0022#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\u005C]^_`abcdefghijklmnopqrstuvwxyz{|}~\u00A0\u00A7\u00A9\u00AB\u00AD\u00B0\u00B7\u00BB\u00C0\u00C1\u00C2\u00C3\u00C4\u00C5\u00C6\u00C7\u00C8\u00C9\u00CA\u00CB\u00CC\u00CD\u00CE\u00CF\u00D0\u00D1\u00D2\u00D3\u00D4\u00D5\u00D6\u00D7\u00D8\u00D9\u00DA\u00DB\u00DC\u00DD\u00DE\u00DF\u00E0\u00E1\u00E2\u00E3\u00E4\u00E5\u00E6\u00E7\u00E8\u00E9\u00EA\u00EB\u00EC\u00ED\u00EE\u00EF\u00F0\u00F1\u00F2\u00F3\u00F4\u00F5\u00F6\u00F7\u00F8\u00F9\u00FA\u00FB\u00FC\u00FD\u00FE\u00FF\u0102\u0103\u015E\u015F\u0162\u0163\u0218\u0219\u021A\u021B\u0400\u0401\u0402\u0403\u0404\u0405\u0406\u0407\u0408\u0409\u040A\u040B\u040C\u040D\u040E\u040F\u0410\u0411\u0412\u0413\u0414\u0415\u0416\u0417\u0418\u0419\u041A\u041B\u041C\u041D\u041E\u041F\u0420\u0421\u0422\u0423\u0424\u0425\u0426\u0427\u0428\u0429\u042A\u042B\u042C\u042D\u042E\u042F\u0430\u0431\u0432\u0433\u0434\u0435\u0436\u0437\u0438\u0439\u043A\u043B\u043C\u043D\u043E\u043F\u0440\u0441\u0442\u0443\u0444\u0445\u0446\u0447\u0448\u0449\u044A\u044B\u044C\u044D\u044E\u044F\u0450\u0451\u0452\u0453\u0454\u0455\u0456\u0457\u0458\u0459\u045A\u045B\u045C\u045D\u045E\u045F\u0490\u0491\u2010\u2013\u2014\u2015\u2018\u2019\u201A\u201C\u201D\u201E\u2022\u2026\u2030\u2039\u203A\u20AC\u2116\u2122\u2212\u2264\u2265";

/** `serifCoverage`, as a type. */
export type SerifGlyph =
  | "\u0020" | "\u0021" | "\u0022" | "\u0023" | "\u0024" | "\u0025" | "\u0026" | "\u0027"
  | "\u0028" | "\u0029" | "\u002A" | "\u002B" | "\u002C" | "\u002D" | "\u002E" | "\u002F"
  | "\u0030" | "\u0031" | "\u0032" | "\u0033" | "\u0034" | "\u0035" | "\u0036" | "\u0037"
  | "\u0038" | "\u0039" | "\u003A" | "\u003B" | "\u003C" | "\u003D" | "\u003E" | "\u003F"
  | "\u0040" | "\u0041" | "\u0042" | "\u0043" | "\u0044" | "\u0045" | "\u0046" | "\u0047"
  | "\u0048" | "\u0049" | "\u004A" | "\u004B" | "\u004C" | "\u004D" | "\u004E" | "\u004F"
  | "\u0050" | "\u0051" | "\u0052" | "\u0053" | "\u0054" | "\u0055" | "\u0056" | "\u0057"
  | "\u0058" | "\u0059" | "\u005A" | "\u005B" | "\u005C" | "\u005D" | "\u005E" | "\u005F"
  | "\u0060" | "\u0061" | "\u0062" | "\u0063" | "\u0064" | "\u0065" | "\u0066" | "\u0067"
  | "\u0068" | "\u0069" | "\u006A" | "\u006B" | "\u006C" | "\u006D" | "\u006E" | "\u006F"
  | "\u0070" | "\u0071" | "\u0072" | "\u0073" | "\u0074" | "\u0075" | "\u0076" | "\u0077"
  | "\u0078" | "\u0079" | "\u007A" | "\u007B" | "\u007C" | "\u007D" | "\u007E" | "\u00A0"
  | "\u00A7" | "\u00A9" | "\u00AB" | "\u00AD" | "\u00B0" | "\u00B7" | "\u00BB" | "\u00C2"
  | "\u00C9" | "\u00CE" | "\u00D7" | "\u00E2" | "\u00E9" | "\u00EE" | "\u00F7" | "\u0102"
  | "\u0103" | "\u015E" | "\u015F" | "\u0162" | "\u0163" | "\u0218" | "\u0219" | "\u021A"
  | "\u021B" | "\u0401" | "\u0410" | "\u0411" | "\u0412" | "\u0413" | "\u0414" | "\u0415"
  | "\u0416" | "\u0417" | "\u0418" | "\u0419" | "\u041A" | "\u041B" | "\u041C" | "\u041D"
  | "\u041E" | "\u041F" | "\u0420" | "\u0421" | "\u0422" | "\u0423" | "\u0424" | "\u0425"
  | "\u0426" | "\u0427" | "\u0428" | "\u0429" | "\u042A" | "\u042B" | "\u042C" | "\u042D"
  | "\u042E" | "\u042F" | "\u0430" | "\u0431" | "\u0432" | "\u0433" | "\u0434" | "\u0435"
  | "\u0436" | "\u0437" | "\u0438" | "\u0439" | "\u043A" | "\u043B" | "\u043C" | "\u043D"
  | "\u043E" | "\u043F" | "\u0440" | "\u0441" | "\u0442" | "\u0443" | "\u0444" | "\u0445"
  | "\u0446" | "\u0447" | "\u0448" | "\u0449" | "\u044A" | "\u044B" | "\u044C" | "\u044D"
  | "\u044E" | "\u044F" | "\u0451" | "\u2010" | "\u2013" | "\u2014" | "\u2015" | "\u2018"
  | "\u2019" | "\u201A" | "\u201C" | "\u201D" | "\u201E" | "\u2022" | "\u2026" | "\u2030"
  | "\u2039" | "\u203A" | "\u20AC" | "\u2116" | "\u2122" | "\u2190" | "\u2191" | "\u2192"
  | "\u2193" | "\u2212" | "\u2264" | "\u2265";

/** `sansCoverage`, as a type. */
export type SansGlyph =
  | "\u0020" | "\u0021" | "\u0022" | "\u0023" | "\u0024" | "\u0025" | "\u0026" | "\u0027"
  | "\u0028" | "\u0029" | "\u002A" | "\u002B" | "\u002C" | "\u002D" | "\u002E" | "\u002F"
  | "\u0030" | "\u0031" | "\u0032" | "\u0033" | "\u0034" | "\u0035" | "\u0036" | "\u0037"
  | "\u0038" | "\u0039" | "\u003A" | "\u003B" | "\u003C" | "\u003D" | "\u003E" | "\u003F"
  | "\u0040" | "\u0041" | "\u0042" | "\u0043" | "\u0044" | "\u0045" | "\u0046" | "\u0047"
  | "\u0048" | "\u0049" | "\u004A" | "\u004B" | "\u004C" | "\u004D" | "\u004E" | "\u004F"
  | "\u0050" | "\u0051" | "\u0052" | "\u0053" | "\u0054" | "\u0055" | "\u0056" | "\u0057"
  | "\u0058" | "\u0059" | "\u005A" | "\u005B" | "\u005C" | "\u005D" | "\u005E" | "\u005F"
  | "\u0060" | "\u0061" | "\u0062" | "\u0063" | "\u0064" | "\u0065" | "\u0066" | "\u0067"
  | "\u0068" | "\u0069" | "\u006A" | "\u006B" | "\u006C" | "\u006D" | "\u006E" | "\u006F"
  | "\u0070" | "\u0071" | "\u0072" | "\u0073" | "\u0074" | "\u0075" | "\u0076" | "\u0077"
  | "\u0078" | "\u0079" | "\u007A" | "\u007B" | "\u007C" | "\u007D" | "\u007E" | "\u00A0"
  | "\u00A7" | "\u00A9" | "\u00AB" | "\u00AD" | "\u00B0" | "\u00B7" | "\u00BB" | "\u00C0"
  | "\u00C1" | "\u00C2" | "\u00C3" | "\u00C4" | "\u00C5" | "\u00C6" | "\u00C7" | "\u00C8"
  | "\u00C9" | "\u00CA" | "\u00CB" | "\u00CC" | "\u00CD" | "\u00CE" | "\u00CF" | "\u00D0"
  | "\u00D1" | "\u00D2" | "\u00D3" | "\u00D4" | "\u00D5" | "\u00D6" | "\u00D7" | "\u00D8"
  | "\u00D9" | "\u00DA" | "\u00DB" | "\u00DC" | "\u00DD" | "\u00DE" | "\u00DF" | "\u00E0"
  | "\u00E1" | "\u00E2" | "\u00E3" | "\u00E4" | "\u00E5" | "\u00E6" | "\u00E7" | "\u00E8"
  | "\u00E9" | "\u00EA" | "\u00EB" | "\u00EC" | "\u00ED" | "\u00EE" | "\u00EF" | "\u00F0"
  | "\u00F1" | "\u00F2" | "\u00F3" | "\u00F4" | "\u00F5" | "\u00F6" | "\u00F7" | "\u00F8"
  | "\u00F9" | "\u00FA" | "\u00FB" | "\u00FC" | "\u00FD" | "\u00FE" | "\u00FF" | "\u0102"
  | "\u0103" | "\u015E" | "\u015F" | "\u0162" | "\u0163" | "\u0218" | "\u0219" | "\u021A"
  | "\u021B" | "\u0400" | "\u0401" | "\u0402" | "\u0403" | "\u0404" | "\u0405" | "\u0406"
  | "\u0407" | "\u0408" | "\u0409" | "\u040A" | "\u040B" | "\u040C" | "\u040D" | "\u040E"
  | "\u040F" | "\u0410" | "\u0411" | "\u0412" | "\u0413" | "\u0414" | "\u0415" | "\u0416"
  | "\u0417" | "\u0418" | "\u0419" | "\u041A" | "\u041B" | "\u041C" | "\u041D" | "\u041E"
  | "\u041F" | "\u0420" | "\u0421" | "\u0422" | "\u0423" | "\u0424" | "\u0425" | "\u0426"
  | "\u0427" | "\u0428" | "\u0429" | "\u042A" | "\u042B" | "\u042C" | "\u042D" | "\u042E"
  | "\u042F" | "\u0430" | "\u0431" | "\u0432" | "\u0433" | "\u0434" | "\u0435" | "\u0436"
  | "\u0437" | "\u0438" | "\u0439" | "\u043A" | "\u043B" | "\u043C" | "\u043D" | "\u043E"
  | "\u043F" | "\u0440" | "\u0441" | "\u0442" | "\u0443" | "\u0444" | "\u0445" | "\u0446"
  | "\u0447" | "\u0448" | "\u0449" | "\u044A" | "\u044B" | "\u044C" | "\u044D" | "\u044E"
  | "\u044F" | "\u0450" | "\u0451" | "\u0452" | "\u0453" | "\u0454" | "\u0455" | "\u0456"
  | "\u0457" | "\u0458" | "\u0459" | "\u045A" | "\u045B" | "\u045C" | "\u045D" | "\u045E"
  | "\u045F" | "\u0490" | "\u0491" | "\u2010" | "\u2013" | "\u2014" | "\u2015" | "\u2018"
  | "\u2019" | "\u201A" | "\u201C" | "\u201D" | "\u201E" | "\u2022" | "\u2026" | "\u2030"
  | "\u2039" | "\u203A" | "\u20AC" | "\u2116" | "\u2122" | "\u2212" | "\u2264" | "\u2265";
