import assert from "node:assert/strict";
import test from "node:test";
import { createHash } from "node:crypto";
import {
  MIN_TOKEN_LENGTH,
  TOKEN_HASH_LENGTH,
  generateToken,
  hashToken,
  isWellFormedToken,
  isWellFormedTokenHash,
  timingSafeEqual,
  timingSafeIndexOf,
} from "./tokens.ts";

test("generateToken produces URL-safe tokens above the entropy floor", () => {
  const token = generateToken();
  // 24 bytes -> 32 base64url characters -> 192 bits.
  assert.equal(token.length, 32);
  assert.match(token, /^[A-Za-z0-9_-]+$/);
  assert.ok(token.length >= MIN_TOKEN_LENGTH);
  assert.ok(!token.includes("="), "no base64 padding");
});

test("generateToken does not repeat", () => {
  const seen = new Set(Array.from({ length: 500 }, () => generateToken()));
  assert.equal(seen.size, 500);
});

test("generateToken refuses to make a weak token", () => {
  assert.throws(() => generateToken(8), /at least 16 bytes/);
});

test("isWellFormedToken enforces alphabet and length", () => {
  assert.ok(isWellFormedToken(generateToken()));
  assert.ok(isWellFormedToken("a".repeat(MIN_TOKEN_LENGTH)));

  assert.ok(!isWellFormedToken("a".repeat(MIN_TOKEN_LENGTH - 1)), "too short");
  assert.ok(!isWellFormedToken("a".repeat(129)), "too long");
  assert.ok(!isWellFormedToken("has spaces in it aaaaaaaaaa"), "space");
  assert.ok(!isWellFormedToken("../../../etc/passwd/aaaaaaaa"), "path traversal");
  assert.ok(!isWellFormedToken("token+with/base64+chars=="), "non-URL-safe base64");
  assert.ok(!isWellFormedToken(""), "empty");
  assert.ok(!isWellFormedToken(undefined), "undefined");
  assert.ok(!isWellFormedToken(12345), "number");
});

test("timingSafeEqual matches only identical strings", async () => {
  const token = generateToken();
  assert.equal(await timingSafeEqual(token, token), true);
  assert.equal(await timingSafeEqual(token, `${token}x`), false);
  assert.equal(await timingSafeEqual(token, token.slice(0, -1)), false);
  assert.equal(await timingSafeEqual("", ""), true);
  assert.equal(await timingSafeEqual("a", "b"), false);
});

test("timingSafeIndexOf finds the entry it should", async () => {
  const tokens = Array.from({ length: 5 }, () => generateToken());
  assert.equal(await timingSafeIndexOf(tokens[3]!, tokens), 3);
  assert.equal(await timingSafeIndexOf(tokens[0]!, tokens), 0);
  assert.equal(await timingSafeIndexOf(generateToken(), tokens), -1);
  assert.equal(await timingSafeIndexOf("anything", []), -1);
});

test("timingSafeIndexOf returns the first of duplicate tokens", async () => {
  const token = generateToken();
  const other = generateToken();
  assert.equal(await timingSafeIndexOf(token, [other, token, token]), 1);
});

test("a near-miss on a long shared prefix still fails", async () => {
  // The property that matters: comparison is over an HMAC, so sharing 31 of 32
  // characters gets an attacker exactly as far as sharing none.
  const token = generateToken();
  const nearMiss = `${token.slice(0, -1)}${token.endsWith("A") ? "B" : "A"}`;
  assert.notEqual(token, nearMiss);
  assert.equal(await timingSafeIndexOf(nearMiss, [token]), -1);
});

test("hashToken agrees with node:crypto, which is what the CLI uses", async () => {
  // `scripts/new-video-token.mjs` prints the hash with node's crypto; the
  // Worker recomputes it with Web Crypto. If these two ever disagreed, every
  // link generated by the CLI would 404 on the live site.
  for (let i = 0; i < 20; i += 1) {
    const token = generateToken();
    assert.equal(
      await hashToken(token),
      createHash("sha256").update(token).digest("base64url"),
    );
  }
});

test("hashToken is 43 base64url characters and stable", async () => {
  const hash = await hashToken("abc");
  assert.equal(hash, "ungWv48Bz-pBQUDeXa4iI7ADYaOWF3qctBD_YfIAFa0"); // known vector
  assert.equal(hash.length, TOKEN_HASH_LENGTH);
  assert.ok(isWellFormedTokenHash(hash));
  assert.equal(await hashToken("abc"), hash);
});

test("hashToken separates near-identical tokens", async () => {
  const token = generateToken();
  assert.notEqual(await hashToken(token), await hashToken(`${token}x`));
  assert.notEqual(await hashToken(token), await hashToken(token.toLowerCase()));
});

test("isWellFormedTokenHash enforces exactly one length", async () => {
  assert.ok(isWellFormedTokenHash(await hashToken(generateToken())));
  assert.ok(!isWellFormedTokenHash("a".repeat(TOKEN_HASH_LENGTH - 1)));
  assert.ok(!isWellFormedTokenHash("a".repeat(TOKEN_HASH_LENGTH + 1)));
  assert.ok(!isWellFormedTokenHash(`${"a".repeat(TOKEN_HASH_LENGTH - 1)}=`));
  assert.ok(!isWellFormedTokenHash(undefined));
  assert.ok(!isWellFormedTokenHash(12345));
});
